@BASE_URL = http://localhost:8080/api

# Captura o ID na hora de registrar um aventureiro para reutilizar dinamicamente.
@ID = {{Registrar_Aventureiro.response.body.id}} 

# @name HealthCheck
GET {{BASE_URL}}/health

###
# @name Registrar_Aventureiro
POST {{BASE_URL}}/aventureiros/create
Content-Type: application/json

{
  "nome": "Pica Pau",
  "classe": "LADINO",
  "nivel": 10,
  "organizacao": {
    "id": 1,
    "ativo": true,
    "nome": "al-qaeda"
  },
  "usuarioCadastro": {
    "id": 1
  }
}

###

# @name Buscar_Aventureiro_Por_ID
GET {{BASE_URL}}/aventureiros/{{ID}}

###

# @name Listar_Aventureiros
# Query Params 👇
# ?page=0&size=10&classe=LADINO&ativo=true&nivelMinimo=1
GET {{BASE_URL}}/aventureiros?page=0&size=10&classe=LADINO&ativo=true&nivelMinimo=1

###

# @name Atualizar_Aventureiro
PATCH  {{BASE_URL}}/aventureiros/{{ID}}
Content-Type: application/json

{
  "nome": "Perna Longa",
  "classe": "GUERREIRO",
  "nivel":30 
}

###

# @name Definir_Companheiro
POST {{BASE_URL}}/companheiros/create/{{ID}}
Content-Type: application/json

{
"nome": "Oddy",
"especie": "CORUJA", 
"lealdade": 70
}
###

# @name Remover_Companheiro
DELETE {{BASE_URL}}/companheiros/delete/{{ID}}
Content-Type: application/json

###

# @name Encerrar_Vínculo_Guilda
PATCH {{BASE_URL}}/aventureiros/guilda/remove/{{ID}}

###

# @name Recrutar_Novamente
PATCH {{BASE_URL}}/aventureiros/guilda/recruit/{{ID}}

###

# @name Buscar_Aventureiro_Por_Nome
GET {{BASE_URL}}/aventureiros/buscar?nome=Perna&page=0&size=10

###

# @name Detalhes_Aventureiro
GET {{BASE_URL}}/aventureiros/{{ID}}/detalhes

###

# @name Listar_Missoes
# Query Params 👇
# ?page=0&size=10&status=EM_ANDAMENTO&nivelPerigo=ALTO
GET {{BASE_URL}}/missoes?page=0&size=10

###

# @name Detalhes_Missao
GET {{BASE_URL}}/missoes/1/detalhes

###

# @name Ranking_Participacao
GET {{BASE_URL}}/aventureiros/ranking

###

# @name Relatorio_Missoes
GET {{BASE_URL}}/missoes/relatorio

