version: "3.9"

services:
# Usei ALTER USER postgres WITH PASSWORD 'postgres'; para fazer a imagem postgres funcionar corretamente
  pg:
    image: leogloriainfnet/postgres-tp2-spring:2.0-mac
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"

  guilda-es:
    image: leogloriainfnet/elastic-tp2-spring:1.0-windows
    container_name: guilda-es
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://guilda-es:9200
    depends_on:
      - guilda-es
